### ISSUE TITLE
npm ssh2 module not working with 7.0.3

### ISSUE THREAD

**Issue by KristianHeider** [ioBroker/ioBroker.javascript#1349]
**Describe the bug**  
For ip tunneling I use ssh2 to update my webserver. On 6.2 script is working.

**To Reproduce**  
```
const Client = require('ssh2').Client; // npm install ssh2
var conn = new Client();
```
ssh2 was added on instance settings javascript 'additional NPM-modules'

**Expected behavior**  
use ssh interface same like with 6.2

**Screenshots & Logfiles**  
2023-06-28 13:46:39.728  - [31merror[39m: javascript.1 (21516) script.js.Check.IPv6: Error: Cannot find module 'ssh2'
2023-06-28 13:46:39.730  - [31merror[39m: javascript.1 (21516)     at Module.require (node:internal/modules/cjs/loader:1098:19)
2023-06-28 13:46:39.732  - [31merror[39m: javascript.1 (21516)     at require (node:internal/modules/cjs/helpers:108:18)
2023-06-28 13:46:39.734  - [31merror[39m: javascript.1 (21516)     at require (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:516:32)
2023-06-28 13:46:39.736  - [31merror[39m: javascript.1 (21516)     at reRegister (script.js.Check.IPv6:79:22)
2023-06-28 13:46:39.738  - [31merror[39m: javascript.1 (21516)     at script.js.Check.IPv6:5:1
2023-06-28 13:46:39.739  - [31merror[39m: javascript.1 (21516)     at script.js.Check.IPv6:108:3
2023-06-28 13:46:39.740  - [31merror[39m: javascript.1 (21516)     at Script.runInContext (node:vm:141:12)

**Versions:**  
 - Adapter version: 7.0.3
 - JS-Controller version: 4.0.24 
 - Node version: 16.20.0 
 - Operating system: raspbian

**Additional context**  
I tried it on different iobroker host with other javascript instance too

**Comment by Apollon77** [comment]
Please restart jvsscript adapter. does it work afterwards?

**Comment by KristianHeider** [comment]
Sorry. seems to work now.
