### ISSUE TITLE
[Bug]: 8.7.5 breaks TypeScript with modules

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.javascript#1652]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

TS

### The problem

```
2024-07-28 00:50:57.966  - info: javascript.0 (377942) Compiling TypeScript source script.js.Automation.Presence
2024-07-28 00:51:00.208  - info: javascript.0 (377942) script.js.Automation.Presence: TypeScript compilation successful
2024-07-28 00:51:00.230  - error: javascript.0 (377942) script.js.Automation.Presence: node:internal/modules/cjs/loader:1143
2024-07-28 00:51:00.230  - error: javascript.0 (377942)   throw err;
2024-07-28 00:51:00.231  - error: javascript.0 (377942)   ^
2024-07-28 00:51:00.231  - error: javascript.0 (377942) Error: Cannot find module 'rxjs/operators'
2024-07-28 00:51:00.231  - error: javascript.0 (377942) Require stack:
2024-07-28 00:51:00.232  - error: javascript.0 (377942) - /opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js
2024-07-28 00:51:00.232  - error: javascript.0 (377942) - /opt/iobroker/node_modules/iobroker.javascript/main.js
2024-07-28 00:51:00.232  - error: javascript.0 (377942)     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
2024-07-28 00:51:00.232  - error: javascript.0 (377942)     at Function.Module._load (node:internal/modules/cjs/loader:981:27)
2024-07-28 00:51:00.232  - error: javascript.0 (377942)     at Module.require (node:internal/modules/cjs/loader:1231:19)
2024-07-28 00:51:00.233  - error: javascript.0 (377942)     at require (node:internal/modules/helpers:177:18)
2024-07-28 00:51:00.233  - error: javascript.0 (377942)     at require (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:548:28)
2024-07-28 00:51:00.233  - error: javascript.0 (377942)     at script.js.Automation.Presence:96:19
2024-07-28 00:51:00.233  - error: javascript.0 (377942)     at Script.runInContext (node:vm:133:12)
```

The same script works with 8.7.3

### Version of nodejs

18

### Version of ioBroker js-controller

6.0.9

### Version of adapter

8.7.5

**Comment by agross** [comment]
I think this is due to the fact that `rxjs` is the module, but `rxjs/operators` is required. So it will never be included in the sandboxes' `mods`.

Time for a test case? These core features break very often recently.
