### ISSUE TITLE
Cannot find module after updating to v5

### ISSUE THREAD

**Issue by xolom** [ioBroker/ioBroker.javascript#798]
Since i updated to v5, the additional `telegraf` module i set properly in adapter settings cannot be found anymore. I get following error message:
`Error: Cannot find module '/opt/iobroker/node_modules/iobroker.javascript/lib/../../telegraf'`

telegraf is installed under `/opt/iobroker/node_modules/iobroker.javascript/node_modules`, so the search path looks messed up. 

I already tried to reinstall the adapter and modules. Any hints to fix that?

**Comment by Apollon77** [comment]
How your script is looking?

**Comment by xolom** [comment]
Here is a minimal example to reproduce the error on my side:
```js
const Telegraf = require('telegraf')

const bot = new Telegraf("abc")
bot.launch()
```

**Comment by Apollon77** [comment]
And the Full error message

**Comment by xolom** [comment]
```
2021-03-08 16:05:10.509  - [31merror[39m: javascript.0 (2418) script.js.test: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.javascript/lib/../../telegraf'
2021-03-08 16:05:10.509  - [31merror[39m: javascript.0 (2418)     at script.js.test:1:18
2021-03-08 16:05:10.509  - [31merror[39m: javascript.0 (2418)     at script.js.test:5:3
2021-03-08 16:05:10.510  - [31merror[39m: javascript.0 (2418)     at Script.runInContext (vm.js:133:20)
2021-03-08 16:05:10.510  - [32minfo[39m: javascript.0 (2418) script.js.test: registered 9 subscriptions and 0 schedules
2021-03-08 16:05:10.511  - [31merror[39m: javascript.0 (2418) script.js.test: TypeError: Telegraf is not a constructor
2021-03-08 16:05:10.511  - [31merror[39m: javascript.0 (2418)     at script.js.test:3:13
2021-03-08 16:05:10.511  - [31merror[39m: javascript.0 (2418)     at script.js.test:5:3
2021-03-08 16:05:10.511  - [31merror[39m: javascript.0 (2418)     at Script.runInContext (vm.js:133:20)
```

**Comment by xolom** [comment]
Maybe that's also important:
```
root@ioBroker:/opt/iobroker# npm list telegraf
iobroker.inst@2.0.3 /opt/iobroker
`-- iobroker.javascript@5.0.12
  `-- telegraf@4.1.2 
```

**Comment by Apollon77** [comment]
Can you please:
* provide nodejs and npm version?
* check in which exact path the tlegraf lib is installed now?
* It seems that npm has restructured packages and so thesy are in an unexpected location. SO is the package in /opt/iobroker/node_modues or in /opt/iobroker/node_modues/iobroker.javascript/node_modules ?

**Comment by xolom** [comment]
```
root@ioBroker:/opt/iobroker# npm -v
6.11.3
root@ioBroker:/opt/iobroker# node -v 
v10.23.3
```

```
root@ioBroker:/opt/iobroker/node_modules/iobroker.javascript/node_modules/telegraf# ll
total 64
drwxr-xr-x+   6 iobroker iobroker  4096 Mar  8 13:33 .
drwxr-xr-x+ 490 iobroker iobroker 20480 Mar  8 13:33 ..
-rw-r--r--+   1 iobroker iobroker  1087 Oct 26  1985 LICENSE
-rw-r--r--+   1 iobroker iobroker 13320 Oct 26  1985 README.md
drwxr-xr-x+   2 iobroker iobroker  4096 Mar  8 13:33 bin
drwxr-xr-x+   4 iobroker iobroker  4096 Mar  8 13:33 lib
-rw-r--r--+   1 iobroker iobroker  3509 Mar  8 13:33 package.json
drwxr-xr-x+   4 iobroker iobroker  4096 Mar  8 13:33 src
drwxr-xr-x+   4 iobroker iobroker  4096 Mar  8 13:33 typings
```

**Comment by Apollon77** [comment]
That’s actually very strange. Could it be that the Telegraf main file somehow got corrupted? Sd card system? Please try to reinstall the package manually there. 

This error could only happen that way if the require of the Telegraf.js fails somehow.

**Comment by xolom** [comment]
Already tried that. No SD card. Running on a SSD. 
Where does the path come from (`/lib/../../telegraf`)? 
I'm also confused, because it works flawlessly with all other packages

**Comment by Apollon77** [comment]
That comes from https://github.com/ioBroker/ioBroker.javascript/blob/b8d2a6b6910865bf7badc2b676b2d42cf4c720ed/lib/sandbox.js#L387-L405 ... means that there must be an exception on require of the package. Maybe add a logging there to see what’s the error.

**Comment by xolom** [comment]
Thanks, that helped to find out that there was an issue with importing packages inside the library. 
Telegraf needs nodejs 12, so i updated nodejs and now everything works fine. Such a simple solution and still so tricky to find out..

Thanks for your help

**Comment by Apollon77** [comment]
But why it was working all time before??

**Comment by xolom** [comment]
Updating the javascript adapter did also update the telegraf package. Before it was an older version, which worked with nodejs 10
