### ISSUE TITLE
4.7.4 breaks rxjs imports

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.javascript#651]
**Describe the bug**  

After upgrading to 4.7.4 my `rxjs` imports no longer work. It seems like the dependencies are not even installed, at least a after downgrading the installation was reported in the log. Refer to #618 for details.

Downgrading to 4.7.3 helps.

**To Reproduce**  
1. Set additional npm module `rxjs` and add a script importing from it
2. Start 4.7.4

**Expected behavior**  

Scripts should work.

**Screenshots & Logfiles**  

```
(2396) script.js.Lights.Remotes: TypeScript compilation failed: import { Observable, merge, combineLatest, Subscription } from 'rxjs'; ^ ERROR: Module '"rxjs"' has no exported member 'Observable' ...
```

**Versions:**  
 - Adapter version: 4.7.4
 - JS-Controller version: 3.1.5
 - Node version: v12.18.3
 - Operating system: Raspberry/docker

**Comment by Apollon77** [comment]
@AlCalzone

**Comment by AlCalzone** [comment]
I'm confused... 4.7.4 only changed the admin UI, nothing related to TypeScript or dependencies as far as I can see. 🤷🏻‍♂️

**Comment by agross** [comment]
Yes, that is what I thought as well. Either #618 is not completely fixed or the update on my host was somehow broken (which would be a first). I'm going to update the adapter once more and let you know what happens.

**Comment by agross** [comment]
Ran the upgrade to 4.7.4 again, this time without errors. I'll let you know if the next update shows the same errors as reported.
