### PR TITLE
Fix type resolution for rxjs in TypeScripts

### LINKED ISSUE #618: Issues with TypeScript scripts using external libs after upgrade from 4.6.17 to 4.6.22
**Describe the bug**  
The working 4.6.17 config has:

*Additional npm modules*: `rxjs`, `rxjs/operators`
*Activate syntax help for these npm modules*: `rxjs`, `rxjs/operators`

No other settings that are non-default.

My scripts import `rxjs` types at the top like this:

```ts
import { concat, Observable, empty, of } from 'rxjs';
import { distinctUntilChanged, tap, share } from 'rxjs/operators';

// More code.
```

This works fine with 4.6.17.

After upgrading to 4.6.22

* The "Additional npm module" `rxjs/operators` throws an error while installing because there is no such package. But I need it somehow for 4.6.17.
* After removing all of `rxjs/operators` from the config the adapter starts OK, but my scripts can no longer load their imports.

```
2020-08-05 08:39:27.237 - error: javascript.0 (2279) script.js.Automation.Bind_Amp_To_TV: TypeScript compilation failed:
--
import { concat, Observable, empty, of } from 'rxjs';
^
ERROR: Cannot find module 'rxjs' or its corresponding type declarations.
import { distinctUntilChanged, tap, share } from 'rxjs/operators';
^
ERROR: Cannot find module 'rxjs/operators' or its corresponding type declarations.
```

**To Reproduce**  
1. Create a script as outlined above and confirm it starts on 4.6.17
1. Upgrade to 4.6.22

**Expected behavior**  
The upgrade should be transparent.

**Versions:**  
 - Adapter version: 4.6.22
 - JS-Controller version: 3.1.5
 - Node version: v12.18.3
 - Operating system: Docker on Raspbian

### PR DESCRIPTION
**Pull request by AlCalzone**
Fixes #618 

@agross this should fix your issue with rxjs. Using these settings, I can use rxjs and rxjs/operators in scripts:
grafik

### CODE REVIEW

**Comment by agross** [comment]
Confirmed to be working. Thanks!

**Comment by Apollon77** [comment]
Ok I can realease tonight
