### ISSUE TITLE
TypeScript compilation failed, Cannot find name XXX

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.javascript#726]
**Describe the bug**  
I have some global scripts. In some of them global variables are defined, e.g. B. loglevels for my scripts.
In older versions (like 4.9.8), other global scripts could use these variables. Now I get the following error:
```
    if (gLoglevel && gLoglevel.substr(0, 5) == 'debug') {
        ^
ERROR: Cannot find name 'gLoglevel'.
```
When I try to declare this variable in the script, I get a different error:
```
2020-12-07 17:29:56.269  - error: javascript.2 (10300) script.js.global.50_logger: TypeScript compilation failed: 
declare export function getCallerName(...param: any[]): string;
        ^
ERROR: 'export' modifier must precede 'declare' modifier.
```
How can I ensure that a global script can also use constants or variables from another global script

**To Reproduce**  
create 2 global scripts
define a variable in the first global script const gMyTest = 'test';
use this variable in the 2nd global script, e.g. B. in a comparison: `if (gMyTest == 'test`) {...}

**Expected behavior**  
I would like to be able to access variables defined in an global script from any other global script, as was possible in older versions of javascript adapter.

**Versions:**  
 - Adapter version: 4.10.7
 - JS-Controller version: 3.1.6
 - Node version: v12.19.1
 - Operating system: Windows 10,  Raspbian 10 (buster)

**Comment by neopholus** [comment]
I have a similar problem. I have a global typescript defining constants.
If I try to use one of the constants, e.g.<const name> in a non-global script, the following error is shown:

ReferenceError: <const name> is not defined

In the 4.10-version it worked as expected, after the update the script does not compile anymore. :(

**Comment by neopholus** [comment]
I checked some versions:
Worked in 4.9.8, does not work since 4.10.1.
