### ISSUE TITLE
Issues with TypeScript scripts using external libs after upgrade from 4.6.17 to 4.6.22

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.javascript#618]
**Describe the bug**  
The working 4.6.17 config has:

*Additional npm modules*: `rxjs`, `rxjs/operators`
*Activate syntax help for these npm modules*: `rxjs`, `rxjs/operators`

No other settings that are non-default.

My scripts import `rxjs` types at the top like this:

```ts
import { concat, Observable, empty, of } from 'rxjs';
import { distinctUntilChanged, tap, share } from 'rxjs/operators';

// More code.
```

This works fine with 4.6.17.

After upgrading to 4.6.22

* The "Additional npm module" `rxjs/operators` throws an error while installing because there is no such package. But I need it somehow for 4.6.17.
* After removing all of `rxjs/operators` from the config the adapter starts OK, but my scripts can no longer load their imports.

```
2020-08-05 08:39:27.237 - error: javascript.0 (2279) script.js.Automation.Bind_Amp_To_TV: TypeScript compilation failed:
--
import { concat, Observable, empty, of } from 'rxjs';
^
ERROR: Cannot find module 'rxjs' or its corresponding type declarations.
import { distinctUntilChanged, tap, share } from 'rxjs/operators';
^
ERROR: Cannot find module 'rxjs/operators' or its corresponding type declarations.
```

**To Reproduce**  
1. Create a script as outlined above and confirm it starts on 4.6.17
1. Upgrade to 4.6.22

**Expected behavior**  
The upgrade should be transparent.

**Versions:**  
 - Adapter version: 4.6.22
 - JS-Controller version: 3.1.5
 - Node version: v12.18.3
 - Operating system: Docker on Raspbian

**Comment by AlCalzone** [comment]
Just some thoughts, I'll have to look at this after my vacation:
`rxjs/...` is not a separate package, but a path inside `rxjs`. This means you cannot install it seperately.

This error might be because we're doing some magic to make TypeScript work inside ioBroker
```
import { distinctUntilChanged, tap, share } from 'rxjs/operators';
^
ERROR: Cannot find module 'rxjs/operators' or its corresponding type declarations.
```
I'm pretty sure this is because I haven't considered this kind of imports.
