### ISSUE TITLE
script.js.vis-Scripts.dvbjs: VMError: Cannot find module 'dvbjs'

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.javascript#287]
When updating the javascript adapter to 4.0.8 or higher (even with latest master branch sources) I receive the following regular errors when my own scripts are executed and which are using certain third-party node modules.

```
2019-01-14 23:57:39.938  - error: javascript.0 script.js.vis-Scripts.dvbjs: VMError: Cannot find module 'dvbjs'
2019-01-14 23:57:39.938  - error: javascript.0     at _require (/opt/iobroker/node_modules/vm2/lib/sandbox.js:246:25)
2019-01-14 23:57:39.938  - error: javascript.0     at Object.<anonymous> (script.js.vis-Scripts.dvbjs:1:13)
2019-01-14 23:57:39.938  - error: javascript.0     at NodeVM.run (/opt/iobroker/node_modules/vm2/lib/main.js:419:27)
2019-01-14 23:57:39.938  - error: javascript.0     at execute (/opt/iobroker/node_modules/iobroker.javascript/main.js:995:16)
2019-01-14 23:57:39.938  - error: javascript.0     at prepareScript (/opt/iobroker/node_modules/iobroker.javascript/main.js:1153:40)
2019-01-14 23:57:39.938  - error: javascript.0     at createActiveObject (/opt/iobroker/node_modules/iobroker.javascript/main.js:1206:20)
2019-01-14 23:57:39.938  - error: javascript.0     at Command.callback (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:205:25)
2019-01-14 23:57:39.938  - error: javascript.0     at normal_reply (/opt/iobroker/node_modules/redis/index.js:726:21)
2019-01-14 23:57:39.938  - error: javascript.0     at RedisClient.return_reply (/opt/iobroker/node_modules/redis/index.js:824:9)
2019-01-14 23:57:39.938  - error: javascript.0     at JavascriptRedisParser.returnReply (/opt/iobroker/node_modules/redis/index.js:192:18)
```

```
2019-01-15 00:00:00.003  - error: javascript.0 Error in callback: VMError: Cannot find module 'node-unifi'
2019-01-15 00:00:00.003  - error: javascript.0     at _require (/opt/iobroker/node_modules/vm2/lib/sandbox.js:246:25)
2019-01-15 00:00:00.003  - error: javascript.0     at check_presence (script.js.Anwesenheit.unifi_pdetect:134:17)
2019-01-15 00:00:00.003  - error: javascript.0     at Proxy.<anonymous> (script.js.Anwesenheit.unifi_pdetect:250:5)
2019-01-15 00:00:00.003  - error: javascript.0     at Object.apply (/opt/iobroker/node_modules/vm2/lib/contextify.js:87:36)
2019-01-15 00:00:00.004  - error: javascript.0     at Job.nodeSchedule.scheduleJob [as job] (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:955:34)
2019-01-15 00:00:00.004  - error: javascript.0     at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
2019-01-15 00:00:00.004  - error: javascript.0     at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:543:11
2019-01-15 00:00:00.004  - error: javascript.0     at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:501:7)
2019-01-15 00:00:00.004  - error: javascript.0     at ontimeout (timers.js:498:11)
2019-01-15 00:00:00.004  - error: javascript.0     at tryOnTimeout (timers.js:323:5)
```

As soon as I downgrade to 4.0.7 these errors disappear and my own scripts start working again.

**Comment by GermanBluefox** [comment]
It is because of vm2. I deactivated it again in 4.0.10

**Comment by jens-maus** [comment]
Indeed it works with 4.0.11 again. Thanks!
