### ISSUE TITLE
ERROR: Type 'Date' is missing the following properties from type 'Date': getWeek, getWeekYear

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.javascript#686]
**Describe the bug**
after updated javascript adapter to 4.9.4 I can't compile anyscripts
global script, TypeScript compilation failed

**To Reproduce**  
start the script

**Expected behavior**  
a compiles and running script

**Screenshots & Logfiles**  
[logfile.txt](https://github.com/ioBroker/ioBroker.javascript/files/5417035/logfile.txt)

**Versions:**  
 - Adapter version: 4.9.4
 - JS-Controller version: 3.1.6
 - Node version: v10.16.3 und v12.19.0
 - Operating system: Windows 2010 und Raspian buster

**Additional context**  
Also, I get compile errors when using a variable from another global script, with version 4,9,3 it's compiled and work
gjRuntimeCfg is defined in 01_configuration:

`interface Ijs {
    selector_needed_anchor: boolean;
}

interface IRuntimeCfg {
    js: Ijs;
}
var gjRuntimeCfg: IRuntimeCfg = {
    'js': {
        'selector_needed_anchor': false
    }
}`

Log:
`2020-10-21 17:40:29.423  - [32minfo[39m: host.NB04(ioBroker02) instance system.adapter.javascript.0 started with pid 5168
2020-10-21 17:40:31.445  - [32minfo[39m: javascript.0 (5168) starting. Version 4.9.4 in C:/iobroker/ioBroker02/node_modules/iobroker.javascript, node: v10.16.3, js-controller: 3.1.6
2020-10-21 17:40:31.523  - [32minfo[39m: javascript.0 (5168) requesting all states
2020-10-21 17:40:31.524  - [32minfo[39m: javascript.0 (5168) requesting all objects
2020-10-21 17:40:32.251  - [32minfo[39m: javascript.0 (5168) received all objects
2020-10-21 17:40:32.263  - [32minfo[39m: javascript.0 (5168) received all states
2020-10-21 17:40:32.390  - [32minfo[39m: javascript.0 (5168) script.js.global.01_configuration: compiling TypeScript source...
2020-10-21 17:40:32.438  - [32minfo[39m: javascript.0 (5168) script.js.global.01_configuration: source code did not change, using cached compilation result...
2020-10-21 17:40:32.439  - [32minfo[39m: javascript.0 (5168) script.js.global.20_utils: compiling TypeScript source...
2020-10-21 17:40:36.324  - [31merror[39m: javascript.0 (5168) script.js.global.20_utils: TypeScript compilation failed: 
        if (gjRuntimeCfg.js.selector_needed_anchor) {
            ^
ERROR: Cannot find name 'gjRuntimeCfg'.

2020-10-21 17:40:36.621  - [32minfo[39m: host.NB04(ioBroker02) stopInstance system.adapter.javascript.0 (force=false, process=true)
`

**Comment by AlCalzone** [comment]
Please share the script(s) that cause(s) the problem

**Comment by AlCalzone** [comment]
And please test version 4.9.5

**Comment by truegreyhound** [comment]
no script needed, following commands producs the error
`    let dtDate: Date = dDate || new Date();`
or
`    let dtDate: Date = dDate;
`
I have checked with the latest version 4.9.6 an the scripts was successfully compiled.
Thanks

**Comment by truegreyhound** [comment]
Error occurs again in the 4.10.x versions.

**Comment by AlCalzone** [comment]
Can you provide a (combination of) script(s) which causes the problem?
Your previous comment only leads to this (correct) error:
```
let dtDate: Date = dDate || new Date(); ^ ERROR: Cannot find name 'dDate'. Did you mean 'dtDate'? 
```

**Comment by truegreyhound** [comment]
global script: 10_date-tools.ts

"use strict";
// @ts-check

function getDateTime(dDate: Date) {
	
    //!P!let dtDate: Date = dDate || new Date();
    let dtDate: Date = dDate;
    if (!(dtDate)) dtDate = new Date();
    
    return formatDate(dtDate, "YYYY-MM-DD, SS:mm");
    
} // getDateTime()


function getDateTimeWseconds(dDate: Date) {

    //!P!let dtDate: Date = dDate || new Date();
    let dtDate: Date = dDate;
    if (!(dtDate)) dtDate = new Date();
    
    return formatDate(dtDate, "YYYY-MM-DD, SS:mm:ss");

} // getDateTimeWseconds()


function diff_days(dDate1: Date, dDate2: Date): number {
	
    //!P!let dTDate1: Date = dDate1 || new Date();
    let dTDate1: Date = dDate1;
    if (!(dTDate1)) dTDate1 = new Date();
    let dTDate2: Date = dDate2 || new Date('1/1/' + dTDate1.getFullYear());

    dTDate1 = new Date(dTDate1.setHours(0,0,0,0));
    dTDate2 = new Date(dTDate2.setHours(0,0,0,0));

    dTDate1 = new Date(dTDate1);
    dTDate2 = new Date(dTDate2);

    let dUDate1: number = Date.UTC(dTDate1.getFullYear(), dTDate1.getMonth(), dTDate1.getDate());
    let dUDate2: number = Date.UTC(dTDate2.getFullYear(), dTDate2.getMonth(), dTDate2.getDate());

    return Math.floor(Math.abs(dUDate1 - dUDate2) / (1000 * 60 * 60 * 24));

}	// diff_days()

**Comment by AlCalzone** [comment]
Using that script, I cannot reproduce with the version that is currently on github:
![grafik](https://user-images.githubusercontent.com/17641229/99991314-28192880-2db5-11eb-940f-3d8205beb2ab.png)

**Comment by truegreyhound** [comment]
this is correct and I can confirm this with the part of the script that I published.
The error message suggests that it is due to this part of the script, I have now also tested with the second part and the error is there again. 
In the second part of the script I extend Date, which probably collides with the new features.
What do I have to change?
the second part of the scipt


/**
 * https://bitsrc.io/gideonshils/js-methods/time/date-add/code
 * @bit
 * @name dateAdd
 * @description Adds the given amount of time to a provided date object. Day, week, month, and year increments maintain the same hour for changes that pass through daylight saving time.
 * @param {Object} original The date object
 * @param {number} increment The amount of time to add (or subtract if negative)
 * @param {string} unit (optional) The time unit to use. Defaults to milliseconds
 * @returns {Object} An updated date object
 * @example
 * ```js
 * var originalDate = new Date('July 1, 2016 18:45:10');
 * 
 * dateAdd(originalDate, 6000, 'milliseconds');  // => 'July 1, 2016 18:45:16'
 * dateAdd(originalDate, 5, 'seconds');          // => 'July 1, 2016 18:45:15'
 * dateAdd(originalDate, 5, 'minutes');          // => 'July 1, 2016 18:45:10'
 * dateAdd(originalDate, 5, 'hours');            // => 'July 1, 2016 23:45:10'
 * dateAdd(originalDate, 5, 'days');             // => 'July 6, 2016 18:45:10'
 * dateAdd(originalDate, 2, 'weeks');            // => 'July 15, 2016 18:45:10'
 * dateAdd(originalDate, 2, 'months');           // => 'September 1, 2016 18:45:10'
 * dateAdd(originalDate, 5, 'years');            // => 'July 1, 2021 18:45:10'
 * dateAdd(originalDate, -1, 'days');            // => 'June 30, 2016 18:45:16'

 * dateAdd(originalDate, 6000);                  // => 'July 1, 2016 18:45:16' - Defaults to ms
 *
 */
function dateAdd(original: Date, increment: number, unit: string): undefined|Date {

	// Return undefiend if first argument isn't a Date object
	if (!(original instanceof Date)) {
		return(undefined);
	}

    let newDate: Date;
    
	switch(unit) {
		case 'seconds':
			// Add number of secodns to current date (ms*1000)
			newDate = new Date(original);
			newDate.setTime(original.getTime() + (increment*1000));

			return newDate;
		case 'minutes':
			// Add number of minutes to current date (ms*1000*60)
			newDate = new Date(original);
			newDate.setTime(original.getTime() + (increment*1000*60));

			return newDate;
		case 'hours':
			// Add number of hours to current date (ms*1000*60*60)
			newDate = new Date(original);
			newDate.setTime(original.getTime() + (increment*1000*60*60));

			return newDate;
		case 'days':
			// Add number of days to current date
			newDate = new Date(original);
			newDate.setDate(original.getDate() + increment);

			return newDate;
		case 'weeks':
			// Add number of weeks to current date
			newDate = new Date(original);
			newDate.setDate(original.getDate() + (increment*7));
			
			return newDate;
		case 'months':
			// Get current date
			let oldDate: number = original.getDate();

			// Increment months (handles year rollover)
			newDate = new Date(original);
			newDate.setMonth(original.getMonth() + increment);
			
			// If new day and old day aren't equal, set new day to last day of last month
			// (handles edge case when adding month to Jan 31st for example. Now goes to Feb 28th)
			if (newDate.getDate() != oldDate) {
				newDate.setDate(0);
			}

			// Handle leap years
			// If old date was Feb 29 (leap year) and new year isn't leap year, set new date to Feb 28
			if (original.getDate() == 29 && !isLeapYear(newDate.getFullYear())) {
				newDate.setMonth(1);
				newDate.setDate(28);
			}
			
			return newDate;
		case 'years':
			// Increment years
			newDate = new Date(original);
			newDate.setFullYear(original.getFullYear() + increment);
			
			// Handle leap years
			// If old date was Feb 29 (leap year) and new year isn't leap year, set new date to Feb 28
			if (original.getDate() == 29 && !isLeapYear(newDate.getFullYear())) {
				newDate.setMonth(1);
				newDate.setDate(28);
			}
			
			return newDate;
		// Defaults to milliseconds
		default:
			newDate = new Date(original);
			newDate.setTime(original.getTime() + increment);
			return newDate;
	}	
}   // dateAdd()


function isLeapYear(year: number) {
	return (((year % 4 === 0) && (year % 100 !== 0)) || (year % 400 === 0));
} // isLeapYear()


// https://www.w3resource.com/javascript-exercises/javascript-date-exercise-24.php
function ISO8601_week_no(dt: Date) {
    let tdt: Date = new Date(dt.valueOf());
    let dayn: number = (dt.getDay() + 6) % 7;

    tdt.setDate(tdt.getDate() - dayn + 3);
    let firstThursday: number = tdt.valueOf();

    tdt.setMonth(0, 1);
    if (tdt.getDay() !== 4) {
        tdt.setMonth(0, 1 + ((4 - tdt.getDay()) + 7) % 7);
    }
    return 1 + Math.ceil((firstThursday - tdt.getTime()) / 604800000);
} // ISO8601_week_no()


// https://stackoverflow.com/questions/7765767/show-week-number-with-javascript
/** 
 * Get the ISO week date week number 
 */
interface Date {
    getWeek(): number;
}
Date.prototype.getWeek = function() {  
    // Create a copy of this date object  
    let target: Date = new Date(this.valueOf());  

    // ISO week date weeks start on monday  
      // so correct the day number  
    let dayNr: number = (this.getDay() + 6) % 7;  

    // ISO 8601 states that week 1 is the week  
    // with the first thursday of that year.  
    // Set the target date to the thursday in the target week  
    target.setDate(target.getDate() - dayNr + 3);  

    // Store the millisecond value of the target date  
    let firstThursday: number = target.valueOf();  

    // Set the target to the first thursday of the year  
    // First set the target to january first  
    target.setMonth(0, 1);  
    // Not a thursday? Correct the date to the next thursday  
    if (target.getDay() != 4) {  
        target.setMonth(0, 1 + ((4 - target.getDay()) + 7) % 7);  
    }

    // The weeknumber is the number of weeks between the   
    // first thursday of the year and the thursday in the target week  
    return (1 + Math.ceil((firstThursday - target.getTime()) / 604800000)); // 604800000 = 7 * 24 * 3600 * 1000   
};

/** 
* Get the ISO week date year number 
*/
interface Date {
    getWeekYear(): number;
}
Date.prototype.getWeekYear = function() {  
    // Create a new date object for the thursday of this week  
    let target: Date  = new Date(this.valueOf());  
    target.setDate(target.getDate() - ((this.getDay() + 6) % 7) + 3);  
    
    return target.getFullYear();  
};


/** 
 * Convert ISO week number and year into date (first day of week)
 */ 
function getDateFromISOWeek(w, y) {
    let simple: Date = new Date(y, 0, 1 + (w - 1) * 7);
    let dow: number = simple.getDay();
    let ISOweekStart: Date = simple;
    
    if (dow <= 4)
        ISOweekStart.setDate(simple.getDate() - simple.getDay() + 1);
    else
        ISOweekStart.setDate(simple.getDate() + 8 - simple.getDay());
    return ISOweekStart;
}


and the log

2020-11-23 19:08:48.472  - [32minfo[39m: host.NB04(ioBroker02) instance system.adapter.javascript.0 started with pid 12544
2020-11-23 19:08:50.119  - [32minfo[39m: javascript.0 (12544) starting. Version 4.10.5 in C:/iobroker/ioBroker02/node_modules/iobroker.javascript, node: v12.19.1, js-controller: 3.1.6
2020-11-23 19:08:50.189  - [32minfo[39m: javascript.0 (12544) requesting all states
2020-11-23 19:08:50.189  - [32minfo[39m: javascript.0 (12544) requesting all objects
2020-11-23 19:08:50.848  - [32minfo[39m: javascript.0 (12544) received all objects
2020-11-23 19:08:50.867  - [32minfo[39m: javascript.0 (12544) received all states
2020-11-23 19:08:50.953  - [32minfo[39m: javascript.0 (12544) script.js.global.test_date_error: compiling TypeScript source...
2020-11-23 19:08:54.748  - [31merror[39m: javascript.0 (12544) script.js.global.test_date_error: TypeScript compilation failed: 
    let tdt: Date = new Date(dt.valueOf());
        ^
ERROR: Type 'Date' is missing the following properties from type 'Date': getWeek, getWeekYear

    let tdt: Date = new Date(dt.valueOf());
                             ^
ERROR: No overload matches this call.
  Overload 1 of 5, '(value: string | number | Date): Date', gave the following error.
    Argument of type 'Object' is not assignable to parameter of type 'string | number | Date'.
      The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
        The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
          Type 'Object' is missing the following properties from type 'Date': toDateString, toTimeString, toLocaleDateString, toLocaleTimeString, and 38 more.
  Overload 2 of 5, '(vd: VarDate): Date', gave the following error.
    Argument of type 'Object' is not assignable to parameter of type 'VarDate'.
      The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
        Property 'VarDate_typekey' is missing in type 'Object' but required in type 'VarDate'.
  Overload 3 of 5, '(value: string | number): Date', gave the following error.
    Argument of type 'Object' is not assignable to parameter of type 'string | number'.
      The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
        Type 'Object' is not assignable to type 'number'.

    let dayn: number = (dt.getDay() + 6) % 7;
                           ^
ERROR: Property 'getDay' does not exist on type 'Date'.

    tdt.setDate(tdt.getDate() - dayn + 3);
        ^
ERROR: Property 'setDate' does not exist on type 'Date'.

    tdt.setDate(tdt.getDate() - dayn + 3);
                    ^
ERROR: Property 'getDate' does not exist on type 'Date'.

    let firstThursday: number = tdt.valueOf();
        ^
ERROR: Type 'Object' is not assignable to type 'number'.

    tdt.setMonth(0, 1);
        ^
ERROR: Property 'setMonth' does not exist on type 'Date'.

    if (tdt.getDay() !== 4) {
            ^
ERROR: Property 'getDay' does not exist on type 'Date'.

        tdt.setMonth(0, 1 + ((4 - tdt.getDay()) + 7) % 7);
            ^
ERROR: Property 'setMonth' does not exist on type 'Date'.

        tdt.setMonth(0, 1 + ((4 - tdt.getDay()) + 7) % 7);
                                      ^
ERROR: Property 'getDay' does not exist on type 'Date'.

    return 1 + Math.ceil((firstThursday - tdt.getTime()) / 604800000);
                                              ^
ERROR: Property 'getTime' does not exist on type 'Date'.

Date.prototype.getWeek = function () {
               ^
ERROR: Property 'getWeek' does not exist on type 'Date'.

    let target: Date = new Date(this.valueOf());
        ^
ERROR: Type 'Date' is not assignable to type 'import("global/test_date_error").Date'.

    target.setDate(target.getDate() - dayNr + 3);
           ^
ERROR: Property 'setDate' does not exist on type 'Date'.

    target.setDate(target.getDate() - dayNr + 3);
                          ^
ERROR: Property 'getDate' does not exist on type 'Date'.

    let firstThursday: number = target.valueOf();
        ^
ERROR: Type 'Object' is not assignable to type 'number'.

    target.setMonth(0, 1);
           ^
ERROR: Property 'setMonth' does not exist on type 'Date'.

    if (target.getDay() != 4) {
               ^
ERROR: Property 'getDay' does not exist on type 'Date'.

        target.setMonth(0, 1 + ((4 - target.getDay()) + 7) % 7);
               ^
ERROR: Property 'setMonth' does not exist on type 'Date'.

        target.setMonth(0, 1 + ((4 - target.getDay()) + 7) % 7);
                                            ^
ERROR: Property 'getDay' does not exist on type 'Date'.

    return (1 + Math.ceil((firstThursday - target.getTime()) / 604800000)); // 604800000 = 7 * 24 * 3600 * 1000   
                                                  ^
ERROR: Property 'getTime' does not exist on type 'Date'.

Date.prototype.getWeekYear = function () {
               ^
ERROR: Property 'getWeekYear' does not exist on type 'Date'.

    let target: Date = new Date(this.valueOf());
        ^
ERROR: Type 'Date' is not assignable to type 'import("global/test_date_error").Date'.

    target.setDate(target.getDate() - ((this.getDay() + 6) % 7) + 3);
           ^
ERROR: Property 'setDate' does not exist on type 'Date'.

    target.setDate(target.getDate() - ((this.getDay() + 6) % 7) + 3);
                          ^
ERROR: Property 'getDate' does not exist on type 'Date'.

    return target.getFullYear();
                  ^
ERROR: Property 'getFullYear' does not exist on type 'Date'.

    let simple: Date = new Date(y, 0, 1 + (w - 1) * 7);
        ^
ERROR: Type 'Date' is not assignable to type 'import("global/test_date_error").Date'.

    let dow: number = simple.getDay();
                             ^
ERROR: Property 'getDay' does not exist on type 'Date'.

        ISOweekStart.setDate(simple.getDate() - simple.getDay() + 1);
                     ^
ERROR: Property 'setDate' does not exist on type 'Date'.

        ISOweekStart.setDate(simple.getDate() - simple.getDay() + 1);
                                    ^
ERROR: Property 'getDate' does not exist on type 'Date'.

        ISOweekStart.setDate(simple.getDate() - simple.getDay() + 1);
                                                       ^
ERROR: Property 'getDay' does not exist on type 'Date'.

        ISOweekStart.setDate(simple.getDate() + 8 - simple.getDay());
                     ^
ERROR: Property 'setDate' does not exist on type 'Date'.

        ISOweekStart.setDate(simple.getDate() + 8 - simple.getDay());
                                    ^
ERROR: Property 'getDate' does not exist on type 'Date'.

        ISOweekStart.setDate(simple.getDate() + 8 - simple.getDay());
                                                           ^
ERROR: Property 'getDay' does not exist on type 'Date'.

**Comment by AlCalzone** [comment]
Thanks, that does seem like it could cause your issues. I'll check it out.

On a side note, please use triple backticks to format your code and logs on GitHub. You can even select the language it uses to highlight:
~~~
```ts
code here
```
~~~

**Comment by AlCalzone** [comment]
Fix is up at #718
