### ISSUE TITLE
Caught by controller[0]: Error: Cannot find module 'typescript' after update to 3.1.5

### ISSUE THREAD

**Issue by peterbaumert** [ioBroker/ioBroker.javascript#602]
Updated to 3.1.5 and got this error:

`

host.iobroker | 2020-06-08 12:26:46.988 | error | instance system.adapter.javascript.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2020-06-08 12:26:46.987 | error | Caught by controller[0]: }
host.iobroker | 2020-06-08 12:26:46.982 | error | Caught by controller[0]: ]
host.iobroker | 2020-06-08 12:26:46.982 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.javascript/main.js'
host.iobroker | 2020-06-08 12:26:46.981 | error | Caught by controller[0]: '/opt/iobroker/node_modules/virtual-tsc/build/index.js',
host.iobroker | 2020-06-08 12:26:46.980 | error | Caught by controller[0]: '/opt/iobroker/node_modules/virtual-tsc/build/compiler.js',
host.iobroker | 2020-06-08 12:26:46.979 | error | Caught by controller[0]: requireStack: [
host.iobroker | 2020-06-08 12:26:46.974 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2020-06-08 12:26:46.973 | error | Caught by controller[0]: {
host.iobroker | 2020-06-08 12:26:46.973 | error | Caught by controller[0]: at internal/main/run_main_module.js:17:47
host.iobroker | 2020-06-08 12:26:46.972 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
host.iobroker | 2020-06-08 12:26:46.971 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.iobroker | 2020-06-08 12:26:46.966 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
host.iobroker | 2020-06-08 12:26:46.965 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.iobroker | 2020-06-08 12:26:46.965 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
host.iobroker | 2020-06-08 12:26:46.964 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:35:24)
host.iobroker | 2020-06-08 12:26:46.963 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
host.iobroker | 2020-06-08 12:26:46.958 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
host.iobroker | 2020-06-08 12:26:46.958 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.iobroker | 2020-06-08 12:26:46.957 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
host.iobroker | 2020-06-08 12:26:46.956 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.iobroker | 2020-06-08 12:26:46.956 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
host.iobroker | 2020-06-08 12:26:46.950 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/virtual-tsc/build/index.js:3:18)
host.iobroker | 2020-06-08 12:26:46.950 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
host.iobroker | 2020-06-08 12:26:46.949 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
host.iobroker | 2020-06-08 12:26:46.949 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.iobroker | 2020-06-08 12:26:46.947 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
host.iobroker | 2020-06-08 12:26:46.946 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.iobroker | 2020-06-08 12:26:46.941 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
host.iobroker | 2020-06-08 12:26:46.940 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/virtual-tsc/build/compiler.js:3:10)
host.iobroker | 2020-06-08 12:26:46.939 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
host.iobroker | 2020-06-08 12:26:46.935 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
host.iobroker | 2020-06-08 12:26:46.932 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:842:27)
host.iobroker | 2020-06-08 12:26:46.931 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
host.iobroker | 2020-06-08 12:26:46.926 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.javascript/main.js
host.iobroker | 2020-06-08 12:26:46.926 | error | Caught by controller[0]: - /opt/iobroker/node_modules/virtual-tsc/build/index.js
host.iobroker | 2020-06-08 12:26:46.925 | error | Caught by controller[0]: - /opt/iobroker/node_modules/virtual-tsc/build/compiler.js
host.iobroker | 2020-06-08 12:26:46.924 | error | Caught by controller[0]: Require stack:
host.iobroker | 2020-06-08 12:26:46.924 | error | Caught by controller[0]: Error: Cannot find module 'typescript'
host.iobroker | 2020-06-08 12:26:46.923 | error | Caught by controller[0]: ^
host.iobroker | 2020-06-08 12:26:46.922 | error | Caught by controller[0]: throw err;
host.iobroker | 2020-06-08 12:26:46.921 | error | Caught by controller[0]: internal/modules/cjs/loader.js:969

`

After doing `npm install typescript` in iobroker dir it works again. Dunno why this happens.

KR
Pete

**Comment by AlCalzone** [comment]
@cmorlok can you please try my fix? In iobroker, install from custom URL https://github.com/ioBroker/ioBroker.javascript/tarball/help-virtual-tsc-find-typescript

**Comment by cmorlok** [comment]
@AlCalzone It works with this patch, thanks
