### ISSUE TITLE
Typescript: import does not work with 4.9.3.

### ISSUE THREAD

**Issue by nooxnet** [ioBroker/ioBroker.javascript#690]
**Describe the bug**  
I wanted to use 
`import * as fs from 'fs';`
but with 4.9.3 I get the error 'An import declaration can only be used in a namespace or module'. I also tried other variations of the import syntax. It works in 4.8.4.

**To Reproduce**  
Create a script with:
`import * as fs from 'fs';`

**Error Message**
javascript.0 (8609) script.js.Test.Test_Import: TypeScript compilation failed: (async () => {import * as fs from 'fs'; ^ ERROR: An import declaration can only be used in a namespace or module.

**Versions:**  
 - Adapter version: 4.9.3
 - JS-Controller version: 3.1.6
 - Node version: v12.18.4
 - Operating system: Raspian

**Additional context**  
Seems like as the whole script is embedded in a function, the import statement is not valid any more. Is there another option how to use modules?

**Comment by AlCalzone** [comment]
Try 4.9.4

**Comment by nooxnet** [comment]
Thanks, it works with 4.9.4.

Sorry, forgot to use `iobroker update` to see the newest version before.
